x-runner-template: &runner-template
  image: myoung34/github-runner:ubuntu-jammy
  restart: unless-stopped
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - runner-cache:/tmp/runner
  environment: &runner-env
    EPHEMERAL: "false"
    DISABLE_AUTO_UPDATE: "false"
    RUNNER_WORKDIR: "/tmp/runner/work"
    LABELS: "self-hosted,linux,ARM64,pi"

services:
  runner-portfolio:
    <<: *runner-template
    container_name: gha-runner-portfolio
    environment:
      <<: *runner-env
      REPO_URL: "https://github.com/rajivghandi767/portfolio-website"
      RUNNER_TOKEN: "${TOKEN_PORTFOLIO}"
      RUNNER_NAME: "pi-portfolio"

  runner-trivia:
    <<: *runner-template
    container_name: gha-runner-trivia
    environment:
      <<: *runner-env
      REPO_URL: "https://github.com/rajivghandi767/country-trivia-web"
      RUNNER_TOKEN: "${TOKEN_TRIVIA}"
      RUNNER_NAME: "pi-trivia"

  runner-prop-ferry:
    <<: *runner-template
    container_name: gha-runner-prop-ferry
    environment:
      <<: *runner-env
      REPO_URL: "https://github.com/rajivghandi767/prop-and-ferry"
      RUNNER_TOKEN: "${TOKEN_PROP_FERRY}"
      RUNNER_NAME: "pi-prop-ferry"

  runner-svt:
    <<: *runner-template
    container_name: gha-runner-svt
    environment:
      <<: *runner-env
      REPO_URL: "https://github.com/rajivghandi767/silicon-valley-trail"
      RUNNER_TOKEN: "${TOKEN_SVT}"
      RUNNER_NAME: "pi-svt"

volumes:
  runner-cache:
