x-runner-template: &runner-template
  image: myoung34/github-runner:ubuntu-jammy
  restart: unless-stopped
  environment: &runner-env
    DISABLE_AUTO_UPDATE: "false"
    RUNNER_WORKDIR: "/tmp/runner/work"
    LABELS: "self-hosted,linux,ARM64,pi"
    EPHEMERAL: "true"

services:
  runner-portfolio:
    <<: *runner-template
    container_name: gha-runner-portfolio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *runner-env
      REPO_URL: "https://github.com/rajivghandi767/portfolio-website"
      APP_ID: "${APP_ID}"
      APP_PRIVATE_KEY: "${APP_PRIVATE_KEY}"
      RUNNER_NAME: "pi-portfolio"

  runner-trivia:
    <<: *runner-template
    container_name: gha-runner-trivia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *runner-env
      REPO_URL: "https://github.com/rajivghandi767/country-trivia-web"
      APP_ID: "${APP_ID}"
      APP_PRIVATE_KEY: "${APP_PRIVATE_KEY}"
      RUNNER_NAME: "pi-trivia"

  runner-prop-ferry:
    <<: *runner-template
    container_name: gha-runner-prop-ferry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *runner-env
      REPO_URL: "https://github.com/rajivghandi767/prop-and-ferry"
      APP_ID: "${APP_ID}"
      APP_PRIVATE_KEY: "${APP_PRIVATE_KEY}"
      RUNNER_NAME: "pi-prop-ferry"

  runner-svt:
    <<: *runner-template
    container_name: gha-runner-svt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      <<: *runner-env
      REPO_URL: "https://github.com/rajivghandi767/silicon-valley-trail"
      APP_ID: "${APP_ID}"
      APP_PRIVATE_KEY: "${APP_PRIVATE_KEY}"
      RUNNER_NAME: "pi-svt"
